### ISSUE TITLE
Add identity management capabilities

### ISSUE THREAD

**Issue by obsidienne** [ueberauth/ueberauth_identity#12]
Hi, 

Do you think those functionalities can be merged in this strategy ?

**Invitable:** sends invites to new users with a sign-up link, allowing the user to create their account with their own password.
**Registerable:** allows anonymous users to register a users email address and password.
**Confirmable:** new accounts require clicking a link in a confirmation email.
**Recoverable:** provides a link to generate a password reset link with token expiry.
**Trackable:** saves login statistics like login counts, timestamps, and IP address for each user.
**Lockable:** locks an account when a specified number of failed sign-in attempts has been exceeded.
**Unlockable With Token:** provides a link to send yourself an unlock email.
**Rememberable:** provides persistent login with 'Remember me?' check box on login page.

**Comment by doomspork** [comment]
Howdy @obsidienne 👋 

I'm not sure `ueberauth_identity` is the place, but this functionality _would_ be excellent.  Something like this could be applicable to Ueberauth, Guardian, or other authentication frameworks.

Any thoughts @hassox?

**Comment by obsidienne** [comment]
If I read the ueberauth read me: "Ueberauth provides only the initial authentication challenge". 
So I though of an identity_management plug, or directly add the management functionalities in identity

**Comment by charleshan** [comment]
This sounds lovely and we definitely need this in our Elixir/Phoenix community!

**Comment by hassox** [comment]
This kind of thing is greath IMHO. Devise in the Ruby world made it pretty trivial to do. So far there is _some_ work in this direction with the Sentinal project.
