### ISSUE TITLE
Question: Persist in User table or Oauth authorization table?

### ISSUE THREAD

**Issue by mikeni** [ueberauth/ueberauth_identity#13]
Looking at an example from

https://github.com/hassox/phoenix_guardian

It seems that hassox, the author, is saving the password in the same sql table as the other Oauth authentications under the token field.  

I know that ueberauth_identity doesn't care how you store or lookup a user from identity authentication but what do you guys recommend,  should i store the user password in the user table in the password field or just along with the rest of the oauth authentications under the token field?

**Comment by doomspork** [comment]
@mikeni I personally store the password on my user table.
