### ISSUE TITLE
Can you customize credentials field?

### ISSUE THREAD

**Issue by terencechow** [ueberauth/ueberauth_identity#14]
How do I modify the credentials field? For example I won't need password confirmation in a login page and I would want the email there. Also under auth.info why are there so many fields? I wouldn't need half of them like phone location etc.

**Comment by doomspork** [comment]
@terencechow not at this time.  PRs are welcome though.  @hassox did you have any plans for supporting this?

**Comment by doomspork** [comment]
@terencechow / @hassox any thoughts on this one or can we close?
