### ISSUE TITLE
Jsonapi & nested attributes

### ISSUE THREAD

**Issue by seanwash** [ueberauth/ueberauth_identity#17]
Hey there,

I'm currently building out an API that conforms to the [Jsonapi.org](http://jsonapi.org/) specification. I noticed that we can account for a nested attribute like `%{user => {email, password}`, but in order to conform to the spec I need to be able to send attributes nested two levels deep, for example:

```
{
  "data": {
    "type": "users",
      "attributes": {
        "email": "sean@wash.com",
        "password": "secret"
      }
    }
}
```

I'd be happy to try to PR this, but I'm still pretty new to Elixir!

**Comment by doomspork** [comment]
This is a great idea @seanwash and it looks like @mikereinmiller took a stab at this in #18, your feedback on the PR is welcomed and encouraged 😀

**Comment by mikereinmiller** [comment]
@doomspork Good call on the test! Let me know any thoughts and feedback you have and I'll start getting a test added for "identity_with_nested_options".  Thanks!

**Comment by seanwash** [comment]
@doomspork @mikereinmiller thanks! I've busy at my day job, but I'll have a chance to check this out in the next couple of days!

**Comment by doomspork** [comment]
@seanwash I believe this has been addressed thanks to @mikereinmiller's PR
