### ISSUE TITLE
undefined function validate_password/1

### ISSUE THREAD

**Issue by nelsonic** [ueberauth/ueberauth_identity#20]
I've tried following the [docs](https://github.com/ueberauth/ueberauth_identity/blame/d3ea795a554ebf7cbfa28c0830b0439df42690d5/README.md#L70) for `ueberauth_identity` but getting:
```
** (CompileError) web/controllers/auth_controller.ex:32: undefined function validate_password/1
```
Error: https://travis-ci.org/dwyl/auth/builds/215054975#L391
Snapshot of code: https://github.com/dwyl/auth/blob/fe8f18a16695b5c2a4ca08c75a02bcd698c202b2/web/controllers/auth_controller.ex#L32

I searched through the `ueberauth` org:
https://github.com/search?q=org%3Aueberauth+validate_password&type=Code
![image](https://cloud.githubusercontent.com/assets/194400/24325614/47d2d1e4-1194-11e7-82b6-5a516e648a12.png)
There's only one place it's referred to and that's in the readme. (_no code examples_)

also checked _all_ 14 answers on StackOverflow http://stackoverflow.com/search?q=ueberauth
(_as instructed in your `CONTRIBUTING.md` but didn't find anything resembling this issue..._)
![image](https://cloud.githubusercontent.com/assets/194400/24323951/650afa1c-1175-11e7-82e8-10d128682472.png)

> There are quite a few questions that have no answers or comments ... 
> So I'm asking my question here in the hope of a response.

Is there an _example_ definition for the `validate_password/1` function?
or can _anybody_ who has successfully implemented `ueberauth_identity` shed some light on this?

**Comment by hassox** [comment]
Hey there. The validate password function mentioned in the readme is not implemented by ueberauth_identity. It's used as an example of what your controller might look like. What it means for each app is different. Sorry for the confusion. You need to implement your own function to validate a password/email/username combo

**Comment by nelsonic** [comment]
@hassox thanks for the quick reply and for clarifying. 
I read the code of https://github.com/ueberauth/ueberauth_example but could not find an _example_ of `validate_password` in the [`auth_controller.ex`](https://github.com/ueberauth/ueberauth_example/blob/b46a084d96da9c1155dd42bc8ac958d3f1513860/web/controllers/auth_controller.ex) ... can you point us to an example implementation? (_please/thanks!_)

**Comment by doomspork** [comment]
@nelsonic maybe we can look at providing a better example but for now @hassox has a project that implements a similar flow but uses difference function names: https://github.com/hassox/phoenix_guardian
