### ISSUE TITLE
Hexdocs link is broken

### ISSUE THREAD

**Issue by mbuhot** [ueberauth/ueberauth_identity#26]
I wasn't able to view the hexdocs for the package, it kept redirecting to `https://hexdocs.pm/ueberauth_identity/extra-readme.html` which results in a 404.

May be just a matter of replacing `extra-readme` with `readme` in the [mix.exs](https://github.com/ueberauth/ueberauth_identity/blob/master/mix.exs#L42) file?

**Comment by doomspork** [comment]
Sorry about that @mbuhot! Would you mind opening a PR for this? If you've not got time I can get to it :tada:
