### ISSUE TITLE
Strategy.Identity: undefined function "validate_password"  in "identity_callback"

### ISSUE THREAD

**Issue by ndrean** [ueberauth/ueberauth_identity#31]
### Steps to Reproduce

Set as the example. Phoenix 1.13

### Expected Result

The identity_callback uses an undefined function "validate_password".

### Actual Result

def identity_callback(%{assigns: %{ueberauth_auth: auth}} = conn, params) do
  case validate_password(auth.credentials)

**Comment by yordis** [comment]
`validate_password` is something that exists in your application, it was used to showcase an example of how it would work, but you need to implement it
